### ISSUE TITLE
Can't remove node

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/floweditor#337]
Repro: 
 - Drag to create new wait
 - Edit action you dragged from into a wait
 - Try to remove the node you created in step one

**Comment by ycleptkellan** [comment]
@ericnewcomer to recap, this is happening because we're giving the node a new `uuid` in `onUpdateRouter`. Blocked pending a discussion w/ the team on whether or not we want to preserve the original `uuid` or keep this behavior and simultaneously update the `uuid` we're pointing to the store's result names map.
