### ISSUE TITLE
Remove `has_value` test

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/floweditor#725]
`has_value` is probably not needed as a test that can be selected in the UI. `has_text` is almost certainly what people want to use as that strips whitespace.

**Comment by nicpottier** [comment]
(we'll need to audit usage / migrate the test)

**Comment by ericnewcomer** [comment]
I don't think we actually need to migrate in this case. We could just remove it from the list and leave existing flows as they are. They would still be able to edit their rules, but once they change the operator, they'd just need to pick a different one (ie, switch over to `has_text`).  I also prefer this since it wouldn't change behavior for any flows that are using it (though I agree it's unlikely anybody would notice).
