### ISSUE TITLE
Card type suggestion

### ISSUE THREAD

**Issue by rafaelbreno** [nyaruka/floweditor#984]
At the moment exists a card called "Waiting for Response" but unfortunately only exists fixed time periods(1 minute, 2 minutes, 3 minutes, ... 1 hour and so on), would be nice if had a option to add custom time periods, e.g 20 seconds.

Following this same issue pattern of time periods, could be added a "Pause for" card, this would allow the "Flow editor" to create a condition to pause the flow execution for a period of time, something like this:
![pause_for_correct](https://user-images.githubusercontent.com/32229014/112857126-e8c25780-9086-11eb-872d-8088df561fdb.png)
This would have option for seconds, minutes, hours, etc; the example above would pause the flow for 1 minute and 20 seconds.

**Comment by rowanseymour** [comment]
Pausing is a frequently requested feature as it sounds simple enough to just put flow execution on pause for a period of time - but it's not clear what the engine should do if the contact sends a message in that time period, or a campaign is fired etc.

That's why we always point people toward timeouts (the continue after X on Waiting for Response nodes) for short pauses, and campaigns for long pauses.

**Comment by ericnewcomer** [comment]
@rowanseymour is correct, we want to direct flow authors to think about this in terms of "No Response" routes on waits. Additionally, sub-minute timeouts are not included by design for scaling purposes.
