### ISSUE TITLE
Currencies should be ordered alphabetically

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/floweditor#986]
A little hard to find specific currencies..

<img width="218" alt="Captura de Pantalla 2021-03-30 a la(s) 09 53 12" src="https://user-images.githubusercontent.com/675558/113037688-44f6ab80-915b-11eb-9ebd-22c3acdf6221.png">

**Comment by rowanseymour** [comment]
Problem here is that they're sorted by name which isn't shown - DZD is first because it's name is `Algerian Dinar`. I think we can just render as `Algerian Dinar (DZD)`

**Comment by susanm74** [comment]
@rowanseymour @ericnewcomer @norkans7 i found the currency element contained within the AirtimeRouterForm, and i see that the visibility "Send Airtime" action is msg, background, and voice, but i'm not seeing this action in any of the dropdowns - is there anything i need to pre-configure within a flow in order to see this action so that i can select it so that i can see the currency dropdown?

**Comment by ericnewcomer** [comment]
I believe you need to configure DT1 on your account page. Don't think there's any validation so you can set it to whatever.

**Comment by susanm74** [comment]
@ericnewcomer ah cool thank you!

**Comment by susanm74** [comment]
@ericnewcomer ok i'm seeing it now, thanks again!
